---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ksv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /kind-shared-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ksv
spec:
  volumeName: pv-ksv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

