---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-job-arguments
data:
  job-args.txt: |
    VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
    1,2021-07-01 00:08:51,2021-07-01 00:13:05,1,.80,1,N,90,68,1,5,3,0.5,0,0,0.3,8.8,2.5
    1,2021-07-01 00:22:39,2021-07-01 00:25:58,1,.90,1,N,113,90,2,5,3,0.5,0,0,0.3,8.8,2.5
    1,2021-07-01 00:48:33,2021-07-01 00:54:58,1,2.80,1,N,88,232,2,10,3,0.5,0,0,0.3,13.8,2.5
    1,2021-07-01 00:59:44,2021-07-01 01:07:09,1,1.40,1,N,79,249,1,7,3,0.5,1.5,0,0.3,12.3,2.5
    1,2021-07-01 00:08:35,2021-07-01 00:16:28,0,2.00,1,N,142,238,1,8.5,3,0.5,0,0,0.3,12.3,2.5
    1,2021-07-01 00:10:49,2021-07-01 00:18:42,1,1.60,1,N,114,90,1,7.5,3,0.5,1.5,0,0.3,12.8,2.5
    1,2021-07-01 00:28:56,2021-07-01 00:36:11,1,1.80,1,N,90,144,1,7.5,3,0.5,2,0,0.3,13.3,2.5
    1,2021-07-01 00:45:10,2021-07-01 00:52:46,1,2.00,1,N,114,48,1,8.5,3,0.5,2.45,0,0.3,14.75,2.5
---
# waar wordt de SA gezet die gebruikt wordt 
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark-ny-cm
spec:
  sparkImage:
    productVersion: 3.5.1
  mode: cluster
  mainApplicationFile: s3a://my-bucket/ny-tlc-report-1.1.0-3.5.1.jar
  mainClass: tech.stackable.demo.spark.NYTLCReport
  volumes:
    - name: cm-job-arguments
      configMap:
        name: cm-job-arguments
  args:
    - "--input /arguments/job-args.txt"
  s3connection:
    inline:
      host: test-minio
      port: 9000
      accessStyle: Path
  sparkConf:
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider"
  driver:
    config:
      volumeMounts:
        - name: cm-job-arguments
          mountPath: /arguments
  executor:
    replicas: 3
    config:
      volumeMounts:
        - name: cm-job-arguments
          mountPath: /arguments
